### ISSUE TITLE
Add --log-msgs json output format

### ISSUE THREAD

**Issue by kornys** [rh-messaging/cli-proton-python#5]

**Comment by jdanekrh** [comment]
The output format (JSON or Python dict) is orthogonal to the content of the output (all fields or interop fields). It should be possible to configure any combination of (JSON, dict) x (interop, all).

The way rh-messaging/cli-java does it is two options, `--log-msgs` and `--out`. I think the solution should go in these lines, although I am open to renaming the parameters (in stages, add new, deprecate old, remove old).

**Comment by jdanekrh** [comment]
Java:  --out=json a zaroven s tim --log-msgs=dict nebo --log-msgs=interop
vidis jak je to nesmyslny? :D interop dava smysl, ale --log-msgs dict --out json, to je total demence
jenze --log-msgs je definovany jako output i, protoze ono jsou zde jeste dalsi --log-msgs, jako je body, nebo upstream
jaky je rozdil mezi dict a upstream?
